apiVersion: v1
kind: Service
metadata:
  name: my-service2
spec:
  type: NodePort
  selector:
    app: nginx-first
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
